services:
  - type: web
    name: ioc-practice
    runtime: node
    repo: https://github.com/Medeiros-Portfolio/ioc-practice
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    envVars: 
      - key: DATABASE_URL
        fromDatabase:
          name: ioc-practice-db
          property: connectionString

databases:
  - name: ioc-practice-db
    databaseName: ioc-practice
    plan: free    
    ipAllowList: []