services:
  - type: web
    name: ioc-practice
    runtime: node
    repo: https://github.com/Medeiros-Portfolio/ioc-practice
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /healthz